# ============================================================
# 渲染包 — 纯函数，从 model / workflow-state 确定性渲染
# 拆自原 engine/renderer.py；按消费者/生命周期分两个模块：
#   docs.py     model → generated/*.md（dev，_internal/generate_docs.py 消费）
#   progress.py workflow-state → progress.md（运行时，adapters/progress_render.py 消费）
# ============================================================
from __future__ import annotations

# 派生文档头（docs.py 与 progress.py 共用；改来源后需重跑 setup.sh 重生成）
_GENERATED_HEADER = "<!-- GENERATED by engine/render — 勿手改，改 model/ 后重新生成 -->\n"

from .docs import (  # noqa: E402  (需先定义 _GENERATED_HEADER)
    render_automation,
    render_templates,
    render_readme,
    render_vocab,
    render_commands,
    render_command_dict,
)
from .progress import (  # noqa: E402
    render_progress,
    event_display,
)
